language: python
cache: pip
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install -r requirements.txt"
  - "pip install ."

script: nosetests

before_deploy:
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  edge: true # opt in to dpl v2
  distributions: "sdist bdist_wheel"
  skip_existing: true
  cleanup: true
  on:
    branch: master
    tags: true
